-- Bun on D-Run: starting data (generated by scripts/seed-sql.mjs; do not edit by hand)
-- Run after schema.sql. Re-running never overwrites changes made in the dashboard.

insert into public.menu_items (id, category, name, description, price, image, available, featured, custom, sort) values
  ('pole-position', 'burgers', 'The Pole Position', 'Double smash patty, American cheese, pickles, onion, D-Run sauce on a toasted potato bun.', 11.49, 'https://images.pexels.com/photos/8365312/pexels-photo-8365312.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, true, false, 10),
  ('single-smash', 'burgers', 'Single Smash', 'One crispy-edged smash patty, American cheese, lettuce, tomato, pickles.', 8.99, 'https://images.pexels.com/photos/4109234/pexels-photo-4109234.jpeg?w=1260&h=750&dpr=1', true, false, false, 20),
  ('burnout', 'burgers', 'The Burnout', 'Double smash, pepper jack, jalapeños, bacon and hot D-Run sauce. Not for the slow lane.', 12.49, 'https://images.pexels.com/photos/8365312/pexels-photo-8365312.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, false, false, 30),
  ('build-your-own', 'burgers', 'Build Your Own Smash', 'Stack it your way in the 3D Burger Builder. Price updates as you build.', 7.99, '', true, false, true, 40),
  ('fries', 'sides', 'Checkered Fries', 'Hand-cut, double-fried, seasoned salt.', 3.99, 'https://images.pexels.com/photos/5652262/pexels-photo-5652262.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, true, false, 50),
  ('loaded-fries', 'sides', 'Pit Stop Loaded Fries', 'Fries, cheese sauce, bacon, jalapeños, D-Run sauce drizzle.', 6.99, 'https://images.pexels.com/photos/8272619/pexels-photo-8272619.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, false, false, 60),
  ('onion-rings', 'sides', 'Onion Rings', 'Thick-cut, beer-battered, golden.', 4.49, '', true, false, false, 70),
  ('vanilla-shake', 'shakes', 'Victory Lap Vanilla Shake', 'Hand-spun vanilla with whipped cream.', 5.49, 'https://images.pexels.com/photos/2059148/pexels-photo-2059148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, true, false, 80),
  ('choc-shake', 'shakes', 'Burnt Rubber Chocolate Shake', 'Rich chocolate, hand-spun.', 5.49, '', true, false, false, 90),
  ('soda', 'shakes', 'Fountain Soda', 'Free refills while you wait.', 2.29, '', true, false, false, 100),
  ('combo-pole', 'combos', 'Pole Position Combo', 'The Pole Position, Checkered Fries and a fountain soda.', 15.99, 'https://images.pexels.com/photos/8365312/pexels-photo-8365312.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', true, false, false, 110),
  ('combo-single', 'combos', 'Single Smash Combo', 'Single Smash, Checkered Fries and a fountain soda.', 13.49, 'https://images.pexels.com/photos/4109234/pexels-photo-4109234.jpeg?w=1260&h=750&dpr=1', true, false, false, 120)
on conflict (id) do nothing;

insert into public.store_info (id, data) values
  (1, '{"name":"Bun on D-Run","tagline":"The fast lane of flavor…","phone":"[PHONE]","facebook":"https://www.facebook.com/search/top?q=Bun%20on%20D-Run","address":{"street":"2850 S Washington Ave","city":"Titusville","state":"FL","zip":"32796","note":"US-1 near Titus Landing, in the old Ice House building"},"hours":{"Monday":{"open":"11:00","close":"21:00","closed":false},"Tuesday":{"open":"11:00","close":"21:00","closed":false},"Wednesday":{"open":"11:00","close":"21:00","closed":false},"Thursday":{"open":"11:00","close":"21:00","closed":false},"Friday":{"open":"11:00","close":"21:00","closed":false},"Saturday":{"open":"11:00","close":"21:00","closed":false},"Sunday":{"open":"11:00","close":"21:00","closed":false}},"announcement":"Opening soon on US-1. Start your engines.","taxRate":0.07}'::jsonb)
on conflict (id) do nothing;
