// Generates supabase/seed.sql from the app's default menu and store info, so the
// database starts out identical to the local demo.
//   node scripts/seed-sql.mjs > supabase/seed.sql
import { build } from 'esbuild'

const entry = `export { DEFAULT_MENU } from './src/data/menu.js'; export { DEFAULT_INFO } from './src/data/business.js'`
const out = await build({ stdin: { contents: entry, resolveDir: process.cwd() }, bundle: true, format: 'esm', write: false })
const { DEFAULT_MENU, DEFAULT_INFO } = await import(`data:text/javascript;base64,${Buffer.from(out.outputFiles[0].text).toString('base64')}`)

const q = (v) => (v == null ? 'null' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`)

const rows = DEFAULT_MENU.map((m, i) =>
  `  (${[m.id, m.category, m.name, m.description, m.price, m.image || '', m.available, !!m.featured, !!m.custom, (i + 1) * 10].map(q).join(', ')})`,
)

console.log(`-- Bun on D-Run: starting data (generated by scripts/seed-sql.mjs; do not edit by hand)
-- Run after schema.sql. Re-running never overwrites changes made in the dashboard.

insert into public.menu_items (id, category, name, description, price, image, available, featured, custom, sort) values
${rows.join(',\n')}
on conflict (id) do nothing;

insert into public.store_info (id, data) values
  (1, ${q(JSON.stringify(DEFAULT_INFO))}::jsonb)
on conflict (id) do nothing;`)
